// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "WPILib.h"
#include "../Commands/DriveNormal.h"

#include "Drive.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Drive::Drive() : Subsystem("Drive") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	frontLeft = RobotMap::driveFrontLeft;
	frontRight = RobotMap::driveFrontRight;
	backLeft = RobotMap::driveBackLeft;
	backRight = RobotMap::driveBackRight;
	mechDrive = RobotMap::driveMechDrive;
	gyro = RobotMap::driveGyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Drive::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());

	SetDefaultCommand(new DriveNormal());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	gyro->Reset();

}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Drive::DriveMethod(float x, float y, float twist)
{
	double angle = gyro->GetAngle();
	mechDrive->MecanumDrive_Cartesian(Drive::FinalAdjust(x), Drive::FinalAdjust(y),Drive::FinalAdjust(twist), angle);
	Wait(0.005);
}


float Drive::Adjust(float x)
{
	if (x>0)
	{
		return x*x/2.0;
	}
	else
	{
		return -1*x*x/2.0;
	}
}

float Drive::ThrottleAdjust(float x){
	float throt = Robot::oi->GetThrot();
	float throt2 = Robot::oi->GetThrot2();
	return  (1- throt*throt*.5)*(1+throt2*throt2);
}

float Drive::FinalAdjust(float x)
{
	return Drive::ThrottleAdjust(x)*Drive::Adjust(x);
}

void Drive::Stop()
{
	mechDrive->MecanumDrive_Cartesian(0,0,0);
}

