// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveFrontLeft = NULL;
SpeedController* RobotMap::driveFrontRight = NULL;
SpeedController* RobotMap::driveBackLeft = NULL;
SpeedController* RobotMap::driveBackRight = NULL;
RobotDrive* RobotMap::driveMechDrive = NULL;
Gyro* RobotMap::driveGyro = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveFrontLeft = new Talon(0);
	lw->AddActuator("Drive", "FrontLeft", (Talon*) driveFrontLeft);
	
	driveFrontRight = new Talon(1);
	lw->AddActuator("Drive", "FrontRight", (Talon*) driveFrontRight);
	
	driveBackLeft = new Talon(3);
	lw->AddActuator("Drive", "BackLeft", (Talon*) driveBackLeft);
	
	driveBackRight = new Talon(2);
	lw->AddActuator("Drive", "BackRight", (Talon*) driveBackRight);
	
	driveMechDrive = new RobotDrive(driveFrontLeft, driveBackLeft,
              driveFrontRight, driveBackRight);
	
	driveMechDrive->SetSafetyEnabled(true);
        driveMechDrive->SetExpiration(0.1);
        driveMechDrive->SetSensitivity(0.5);
        driveMechDrive->SetMaxOutput(1.0);

	driveGyro = new Gyro(0);
	lw->AddSensor("Drive", "Gyro", driveGyro);
	driveGyro->SetSensitivity(0.007);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveMechDrive->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
}
